name: crowdfunding
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_overrides:
  cloud_firestore_platform_interface: 5.4.13

dependencies:
  flutter:
    sdk: flutter
  # Shimmer
  shimmer: ^2.0.0
  # Local Storage
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^5.0.2
  # Internet Checker
  connectivity_plus: ^2.1.0
  # State Management
  flutter_bloc: ^7.3.0
  # Dialog
  fluttertoast: ^8.0.8
  ndialog: ^4.1.0
  # Service locator
  get_it: ^7.1.3
  # Chnage app package name
  change_app_package_name: ^1.0.0
  # Internet
  dio: ^4.0.0
  http: ^0.13.3
  # Value Equality
  equatable: ^2.0.3
  # Image Picker
  image_picker: ^0.8.2
  # Crop Image
  image_cropper: ^1.4.1
  # Compress Image
  flutter_native_image: ^0.0.6+1
  # Change app launcher icons
  flutter_launcher_icons: ^0.9.2
  # Firebase
  firebase_core: ^1.6.0
  # firebase_analytics: ^9.0.4
  cloud_firestore: ^2.5.1
  # Check Update app status
  new_version: ^0.2.3
  # File picker
  file_picker: ^4.3.2
  # Progress Indicator
  percent_indicator: ^4.0.0
  # SVG
  flutter_svg: ^0.22.0
  # intl
  intl: ^0.17.0
  # keyboard
  numeric_keyboard: ^1.1.0
  # local auth
  local_auth: ^1.1.7
  # Permission Handler
  permission_handler: ^8.1.6
  # Path provider
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  web3dart: ^2.3.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/contracts/
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/